2023-11-20 14:09:57 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2023-11-20 14:09:57 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2023-11-20 14:10:09 [INFO    ] (basehttp.log_message) "GET /users/login/ HTTP/1.1" 200 14121
2023-11-20 14:10:09 [INFO    ] (basehttp.log_message) "GET /users/login/ HTTP/1.1" 200 14121
2023-11-20 17:24:34 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2023-11-20 17:24:34 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2023-11-20 17:24:38 [INFO    ] (basehttp.log_message) "GET / HTTP/1.1" 200 12783
2023-11-20 17:24:38 [INFO    ] (basehttp.log_message) "GET / HTTP/1.1" 200 12783
2023-11-20 17:24:38 [WARNING ] (log.log_response) Not Found: /favicon.ico
2023-11-20 17:24:38 [WARNING ] (log.log_response) Not Found: /favicon.ico
2023-11-20 17:24:38 [WARNING ] (basehttp.log_message) "GET /favicon.ico HTTP/1.1" 404 12657
2023-11-20 17:24:38 [WARNING ] (basehttp.log_message) "GET /favicon.ico HTTP/1.1" 404 12657
2023-11-20 17:24:42 [ERROR   ] (log.log_response) Internal Server Error: /products/
Traceback (most recent call last):
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django_redis\cache.py", line 29, in _decorator
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django_redis\cache.py", line 99, in _get
    return self.client.get(key, default=default, version=version, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django_redis\client\default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 10061 connecting to 127.0.0.1:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\views\generic\list.py", line 157, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\mystore\products\views.py", line 32, in get_context_data
    categories = cache.get('categories')
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\debug_toolbar\panels\cache.py", line 42, in wrapper
    return panel._record_call(cache, name, original_method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\debug_toolbar\panels\cache.py", line 149, in _record_call
    value = original_method(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django_redis\cache.py", line 92, in get
    value = self._get(key, default, version, client)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django_redis\cache.py", line 36, in _decorator
    raise e.__cause__
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django_redis\client\default.py", line 258, in get
    value = client.get(key)
            ^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\redis\commands\core.py", line 1816, in get
    return self.execute_command("GET", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\redis\client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\redis\connection.py", line 1461, in get_connection
    connection.connect()
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\redis\connection.py", line 713, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
2023-11-20 17:24:42 [ERROR   ] (log.log_response) Internal Server Error: /products/
Traceback (most recent call last):
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django_redis\cache.py", line 29, in _decorator
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django_redis\cache.py", line 99, in _get
    return self.client.get(key, default=default, version=version, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django_redis\client\default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 10061 connecting to 127.0.0.1:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\views\generic\list.py", line 157, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\mystore\products\views.py", line 32, in get_context_data
    categories = cache.get('categories')
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\debug_toolbar\panels\cache.py", line 42, in wrapper
    return panel._record_call(cache, name, original_method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\debug_toolbar\panels\cache.py", line 149, in _record_call
    value = original_method(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django_redis\cache.py", line 92, in get
    value = self._get(key, default, version, client)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django_redis\cache.py", line 36, in _decorator
    raise e.__cause__
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django_redis\client\default.py", line 258, in get
    value = client.get(key)
            ^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\redis\commands\core.py", line 1816, in get
    return self.execute_command("GET", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\redis\client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\redis\connection.py", line 1461, in get_connection
    connection.connect()
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\redis\connection.py", line 713, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
2023-11-20 17:24:42 [ERROR   ] (basehttp.log_message) "GET /products/ HTTP/1.1" 500 153914
2023-11-20 17:24:42 [ERROR   ] (basehttp.log_message) "GET /products/ HTTP/1.1" 500 153914
2023-11-20 17:24:44 [INFO    ] (basehttp.log_message) "GET /users/login/ HTTP/1.1" 200 14122
2023-11-20 17:24:44 [INFO    ] (basehttp.log_message) "GET /users/login/ HTTP/1.1" 200 14122
2023-11-20 17:41:41 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2023-11-20 17:41:41 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2023-11-20 17:41:43 [INFO    ] (basehttp.log_message) "GET / HTTP/1.1" 200 12783
2023-11-20 17:41:43 [INFO    ] (basehttp.log_message) "GET / HTTP/1.1" 200 12783
2023-11-20 17:41:46 [INFO    ] (basehttp.log_message) "GET /admin HTTP/1.1" 301 0
2023-11-20 17:41:46 [INFO    ] (basehttp.log_message) "GET /admin HTTP/1.1" 301 0
2023-11-20 17:41:46 [INFO    ] (basehttp.log_message) "GET /admin/ HTTP/1.1" 302 0
2023-11-20 17:41:46 [INFO    ] (basehttp.log_message) "GET /admin/ HTTP/1.1" 302 0
2023-11-20 17:41:47 [INFO    ] (basehttp.log_message) "GET /admin/login/?next=/admin/ HTTP/1.1" 200 12097
2023-11-20 17:41:47 [INFO    ] (basehttp.log_message) "GET /admin/login/?next=/admin/ HTTP/1.1" 200 12097
2023-11-20 17:41:47 [INFO    ] (basehttp.log_message) "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2271
2023-11-20 17:41:47 [INFO    ] (basehttp.log_message) "GET /static/admin/css/base.css HTTP/1.1" 200 19513
2023-11-20 17:41:47 [INFO    ] (basehttp.log_message) "GET /static/admin/css/base.css HTTP/1.1" 200 19513
2023-11-20 17:41:47 [INFO    ] (basehttp.log_message) "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2271
2023-11-20 17:41:47 [INFO    ] (basehttp.log_message) "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
2023-11-20 17:41:47 [INFO    ] (basehttp.log_message) "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
2023-11-20 17:41:47 [INFO    ] (basehttp.log_message) "GET /static/admin/css/responsive.css HTTP/1.1" 200 18545
2023-11-20 17:41:47 [INFO    ] (basehttp.log_message) "GET /static/admin/css/responsive.css HTTP/1.1" 200 18545
2023-11-20 17:41:47 [INFO    ] (basehttp.log_message) "GET /static/admin/css/login.css HTTP/1.1" 200 939
2023-11-20 17:41:47 [INFO    ] (basehttp.log_message) "GET /static/admin/css/login.css HTTP/1.1" 200 939
2023-11-20 17:41:47 [INFO    ] (basehttp.log_message) "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 1360
2023-11-20 17:41:47 [INFO    ] (basehttp.log_message) "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 1360
2023-11-20 17:41:47 [INFO    ] (basehttp.log_message) "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
2023-11-20 17:41:47 [INFO    ] (basehttp.log_message) "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
2023-11-20 17:41:47 [INFO    ] (basehttp.log_message) "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
2023-11-20 17:41:47 [INFO    ] (basehttp.log_message) "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
2023-11-20 17:41:49 [INFO    ] (basehttp.log_message) "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
2023-11-20 17:41:49 [INFO    ] (basehttp.log_message) "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
2023-11-20 17:41:49 [INFO    ] (basehttp.log_message) "GET /admin/ HTTP/1.1" 200 22114
2023-11-20 17:41:49 [INFO    ] (basehttp.log_message) "GET /admin/ HTTP/1.1" 200 22114
2023-11-20 17:41:49 [INFO    ] (basehttp.log_message) "GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
2023-11-20 17:41:49 [INFO    ] (basehttp.log_message) "GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
2023-11-20 17:41:49 [INFO    ] (basehttp.log_message) "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
2023-11-20 17:41:49 [INFO    ] (basehttp.log_message) "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
2023-11-20 17:41:49 [INFO    ] (basehttp.log_message) "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
2023-11-20 17:41:49 [INFO    ] (basehttp.log_message) "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
2023-11-20 17:41:49 [INFO    ] (basehttp.log_message) "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
2023-11-20 17:41:49 [INFO    ] (basehttp.log_message) "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
2023-11-20 17:41:49 [INFO    ] (basehttp.log_message) "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
2023-11-20 17:41:49 [INFO    ] (basehttp.log_message) "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /admin/sites/site/ HTTP/1.1" 200 21485
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /admin/sites/site/ HTTP/1.1" 200 21485
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/js/core.js HTTP/1.1" 200 5698
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/js/core.js HTTP/1.1" 200 5698
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/css/changelists.css HTTP/1.1" 200 6874
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/css/changelists.css HTTP/1.1" 200 6874
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 287630
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 287630
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/js/actions.js HTTP/1.1" 200 7867
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/js/actions.js HTTP/1.1" 200 7867
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/js/urlify.js HTTP/1.1" 200 7902
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/js/urlify.js HTTP/1.1" 200 7902
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 5984
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 5984
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/img/search.svg HTTP/1.1" 200 458
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/img/search.svg HTTP/1.1" 200 458
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
2023-11-20 17:41:51 [INFO    ] (basehttp.log_message) "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
2023-11-20 17:41:56 [INFO    ] (basehttp.log_message) "GET /admin/ HTTP/1.1" 200 22114
2023-11-20 17:41:56 [INFO    ] (basehttp.log_message) "GET /admin/ HTTP/1.1" 200 22114
2023-11-20 17:42:10 [INFO    ] (basehttp.log_message) "GET / HTTP/1.1" 200 13765
2023-11-20 17:42:10 [INFO    ] (basehttp.log_message) "GET / HTTP/1.1" 200 13765
2023-11-20 17:44:44 [INFO    ] (autoreload.trigger_reload) C:\Users\Дом\Desktop\mystore-server\mystore\mystore\settings.py changed, reloading.
2023-11-20 17:44:44 [INFO    ] (autoreload.trigger_reload) C:\Users\Дом\Desktop\mystore-server\mystore\mystore\settings.py changed, reloading.
2023-11-20 17:44:46 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2023-11-20 17:44:46 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2023-11-20 17:45:03 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2023-11-20 17:45:03 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2023-11-20 17:45:05 [INFO    ] (basehttp.log_message) "GET / HTTP/1.1" 200 13765
2023-11-20 17:45:05 [INFO    ] (basehttp.log_message) "GET / HTTP/1.1" 200 13765
2023-11-20 17:45:07 [INFO    ] (basehttp.log_message) "GET /users/logout/ HTTP/1.1" 302 0
2023-11-20 17:45:07 [INFO    ] (basehttp.log_message) "GET /users/logout/ HTTP/1.1" 302 0
2023-11-20 17:45:07 [INFO    ] (basehttp.log_message) "GET / HTTP/1.1" 200 12783
2023-11-20 17:45:07 [INFO    ] (basehttp.log_message) "GET / HTTP/1.1" 200 12783
2023-11-20 17:45:08 [ERROR   ] (log.log_response) Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\test\utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\test\utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\templatetags\socialaccount.py", line 20, in provider_login_url
    provider = adapter.get_provider(request, provider)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\adapter.py", line 206, in get_provider
    app = self.get_app(request, provider=provider)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\adapter.py", line 288, in get_app
    raise MultipleObjectsReturned
django.core.exceptions.MultipleObjectsReturned
2023-11-20 17:45:08 [ERROR   ] (log.log_response) Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\test\utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\test\utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\templatetags\socialaccount.py", line 20, in provider_login_url
    provider = adapter.get_provider(request, provider)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\adapter.py", line 206, in get_provider
    app = self.get_app(request, provider=provider)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\adapter.py", line 288, in get_app
    raise MultipleObjectsReturned
django.core.exceptions.MultipleObjectsReturned
2023-11-20 17:45:08 [ERROR   ] (basehttp.log_message) "GET /users/login/ HTTP/1.1" 500 175743
2023-11-20 17:45:08 [ERROR   ] (basehttp.log_message) "GET /users/login/ HTTP/1.1" 500 175743
2023-11-20 17:46:19 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2023-11-20 17:46:19 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2023-11-20 17:46:21 [ERROR   ] (log.log_response) Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\test\utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\test\utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\templatetags\socialaccount.py", line 20, in provider_login_url
    provider = adapter.get_provider(request, provider)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\adapter.py", line 206, in get_provider
    app = self.get_app(request, provider=provider)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\adapter.py", line 288, in get_app
    raise MultipleObjectsReturned
django.core.exceptions.MultipleObjectsReturned
2023-11-20 17:46:21 [ERROR   ] (log.log_response) Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\test\utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\test\utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\templatetags\socialaccount.py", line 20, in provider_login_url
    provider = adapter.get_provider(request, provider)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\adapter.py", line 206, in get_provider
    app = self.get_app(request, provider=provider)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\adapter.py", line 288, in get_app
    raise MultipleObjectsReturned
django.core.exceptions.MultipleObjectsReturned
2023-11-20 17:46:21 [ERROR   ] (basehttp.log_message) "GET /users/login/ HTTP/1.1" 500 175909
2023-11-20 17:46:21 [ERROR   ] (basehttp.log_message) "GET /users/login/ HTTP/1.1" 500 175909
2023-11-20 17:46:22 [ERROR   ] (log.log_response) Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\test\utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\test\utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\templatetags\socialaccount.py", line 20, in provider_login_url
    provider = adapter.get_provider(request, provider)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\adapter.py", line 206, in get_provider
    app = self.get_app(request, provider=provider)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\adapter.py", line 288, in get_app
    raise MultipleObjectsReturned
django.core.exceptions.MultipleObjectsReturned
2023-11-20 17:46:22 [ERROR   ] (log.log_response) Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\test\utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\test\utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\templatetags\socialaccount.py", line 20, in provider_login_url
    provider = adapter.get_provider(request, provider)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\adapter.py", line 206, in get_provider
    app = self.get_app(request, provider=provider)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\adapter.py", line 288, in get_app
    raise MultipleObjectsReturned
django.core.exceptions.MultipleObjectsReturned
2023-11-20 17:46:22 [ERROR   ] (basehttp.log_message) "GET /users/login/ HTTP/1.1" 500 175906
2023-11-20 17:46:22 [ERROR   ] (basehttp.log_message) "GET /users/login/ HTTP/1.1" 500 175906
2023-11-20 17:50:28 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2023-11-20 17:50:28 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2023-11-20 17:50:30 [INFO    ] (basehttp.log_message) "GET / HTTP/1.1" 200 12783
2023-11-20 17:50:30 [INFO    ] (basehttp.log_message) "GET / HTTP/1.1" 200 12783
2023-11-20 17:50:32 [ERROR   ] (log.log_response) Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\test\utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\test\utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\templatetags\socialaccount.py", line 20, in provider_login_url
    provider = adapter.get_provider(request, provider)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\adapter.py", line 206, in get_provider
    app = self.get_app(request, provider=provider)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\adapter.py", line 288, in get_app
    raise MultipleObjectsReturned
django.core.exceptions.MultipleObjectsReturned
2023-11-20 17:50:32 [ERROR   ] (log.log_response) Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\test\utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\test\utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\django\template\library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\templatetags\socialaccount.py", line 20, in provider_login_url
    provider = adapter.get_provider(request, provider)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\adapter.py", line 206, in get_provider
    app = self.get_app(request, provider=provider)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\Desktop\mystore-server\venv\Lib\site-packages\allauth\socialaccount\adapter.py", line 288, in get_app
    raise MultipleObjectsReturned
django.core.exceptions.MultipleObjectsReturned
2023-11-20 17:50:32 [ERROR   ] (basehttp.log_message) "GET /users/login/ HTTP/1.1" 500 175701
2023-11-20 17:50:32 [ERROR   ] (basehttp.log_message) "GET /users/login/ HTTP/1.1" 500 175701
2023-11-20 17:52:55 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialapp/ HTTP/1.1" 302 0
2023-11-20 17:52:55 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialapp/ HTTP/1.1" 302 0
2023-11-20 17:52:55 [INFO    ] (basehttp.log_message) "GET /admin/login/?next=/admin/socialaccount/socialapp/ HTTP/1.1" 200 12172
2023-11-20 17:52:55 [INFO    ] (basehttp.log_message) "GET /admin/login/?next=/admin/socialaccount/socialapp/ HTTP/1.1" 200 12172
2023-11-20 17:52:57 [INFO    ] (basehttp.log_message) "POST /admin/login/?next=/admin/socialaccount/socialapp/ HTTP/1.1" 302 0
2023-11-20 17:52:57 [INFO    ] (basehttp.log_message) "POST /admin/login/?next=/admin/socialaccount/socialapp/ HTTP/1.1" 302 0
2023-11-20 17:52:57 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialapp/ HTTP/1.1" 200 20860
2023-11-20 17:52:57 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialapp/ HTTP/1.1" 200 20860
2023-11-20 17:52:57 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 17:52:57 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 17:53:00 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialapp/1/change/ HTTP/1.1" 200 24992
2023-11-20 17:53:00 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialapp/1/change/ HTTP/1.1" 200 24992
2023-11-20 17:53:00 [INFO    ] (basehttp.log_message) "GET /static/admin/css/forms.css HTTP/1.1" 200 8804
2023-11-20 17:53:00 [INFO    ] (basehttp.log_message) "GET /static/admin/css/forms.css HTTP/1.1" 200 8804
2023-11-20 17:53:00 [INFO    ] (basehttp.log_message) "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4360
2023-11-20 17:53:00 [INFO    ] (basehttp.log_message) "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4360
2023-11-20 17:53:00 [INFO    ] (basehttp.log_message) "GET /static/admin/css/widgets.css HTTP/1.1" 200 11097
2023-11-20 17:53:00 [INFO    ] (basehttp.log_message) "GET /static/admin/css/widgets.css HTTP/1.1" 200 11097
2023-11-20 17:53:00 [INFO    ] (basehttp.log_message) "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 12350
2023-11-20 17:53:00 [INFO    ] (basehttp.log_message) "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 12350
2023-11-20 17:53:00 [INFO    ] (basehttp.log_message) "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 492
2023-11-20 17:53:00 [INFO    ] (basehttp.log_message) "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 492
2023-11-20 17:53:00 [INFO    ] (basehttp.log_message) "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
2023-11-20 17:53:00 [INFO    ] (basehttp.log_message) "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
2023-11-20 17:53:00 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 17:53:00 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 17:53:00 [INFO    ] (basehttp.log_message) "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
2023-11-20 17:53:00 [INFO    ] (basehttp.log_message) "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
2023-11-20 17:53:00 [INFO    ] (basehttp.log_message) "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
2023-11-20 17:53:00 [INFO    ] (basehttp.log_message) "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
2023-11-20 17:53:00 [INFO    ] (basehttp.log_message) "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
2023-11-20 17:53:00 [INFO    ] (basehttp.log_message) "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
2023-11-20 17:53:14 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialtoken/ HTTP/1.1" 200 21107
2023-11-20 17:53:14 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialtoken/ HTTP/1.1" 200 21107
2023-11-20 17:53:14 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 17:53:14 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 17:53:16 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialaccount/ HTTP/1.1" 200 19955
2023-11-20 17:53:16 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialaccount/ HTTP/1.1" 200 19955
2023-11-20 17:53:16 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 17:53:16 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 17:53:20 [INFO    ] (basehttp.log_message) "GET /admin/sites/site/ HTTP/1.1" 200 21485
2023-11-20 17:53:20 [INFO    ] (basehttp.log_message) "GET /admin/sites/site/ HTTP/1.1" 200 21485
2023-11-20 17:53:20 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 17:53:20 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 17:53:36 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialapp/ HTTP/1.1" 200 20859
2023-11-20 17:53:36 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialapp/ HTTP/1.1" 200 20859
2023-11-20 17:53:36 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 17:53:36 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 17:54:14 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialapp/1/change/ HTTP/1.1" 200 24992
2023-11-20 17:54:14 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialapp/1/change/ HTTP/1.1" 200 24992
2023-11-20 17:54:14 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 17:54:14 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 17:54:20 [INFO    ] (basehttp.log_message) "POST /admin/socialaccount/socialapp/1/change/ HTTP/1.1" 302 0
2023-11-20 17:54:20 [INFO    ] (basehttp.log_message) "POST /admin/socialaccount/socialapp/1/change/ HTTP/1.1" 302 0
2023-11-20 17:54:20 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialapp/ HTTP/1.1" 200 21112
2023-11-20 17:54:20 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialapp/ HTTP/1.1" 200 21112
2023-11-20 17:54:20 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 17:54:20 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 17:54:20 [INFO    ] (basehttp.log_message) "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
2023-11-20 17:54:20 [INFO    ] (basehttp.log_message) "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
2023-11-20 17:54:31 [INFO    ] (autoreload.trigger_reload) C:\Users\Дом\Desktop\mystore-server\mystore\mystore\settings.py changed, reloading.
2023-11-20 17:54:31 [INFO    ] (autoreload.trigger_reload) C:\Users\Дом\Desktop\mystore-server\mystore\mystore\settings.py changed, reloading.
2023-11-20 17:54:33 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2023-11-20 17:54:33 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2023-11-20 17:54:34 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialapp/ HTTP/1.1" 200 20859
2023-11-20 17:54:34 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialapp/ HTTP/1.1" 200 20859
2023-11-20 17:54:34 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 17:54:34 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 17:54:37 [INFO    ] (basehttp.log_message) "GET / HTTP/1.1" 200 13764
2023-11-20 17:54:37 [INFO    ] (basehttp.log_message) "GET / HTTP/1.1" 200 13764
2023-11-20 17:54:39 [INFO    ] (basehttp.log_message) "GET /users/logout/ HTTP/1.1" 302 0
2023-11-20 17:54:39 [INFO    ] (basehttp.log_message) "GET /users/logout/ HTTP/1.1" 302 0
2023-11-20 17:54:39 [INFO    ] (basehttp.log_message) "GET / HTTP/1.1" 200 12783
2023-11-20 17:54:39 [INFO    ] (basehttp.log_message) "GET / HTTP/1.1" 200 12783
2023-11-20 17:54:39 [INFO    ] (basehttp.log_message) "GET /users/login/ HTTP/1.1" 200 14122
2023-11-20 17:54:39 [INFO    ] (basehttp.log_message) "GET /users/login/ HTTP/1.1" 200 14122
2023-11-20 17:54:42 [INFO    ] (basehttp.log_message) "GET /accounts/github/login/ HTTP/1.1" 200 11085
2023-11-20 17:54:42 [INFO    ] (basehttp.log_message) "GET /accounts/github/login/ HTTP/1.1" 200 11085
2023-11-20 17:54:43 [INFO    ] (basehttp.log_message) "POST /accounts/github/login/ HTTP/1.1" 302 0
2023-11-20 17:54:43 [INFO    ] (basehttp.log_message) "POST /accounts/github/login/ HTTP/1.1" 302 0
2023-11-20 17:54:45 [INFO    ] (basehttp.log_message) "GET /accounts/github/login/callback/?code=262761f1a7dd111378b0&state=CZ0dywjbdVWwstxy HTTP/1.1" 302 0
2023-11-20 17:54:45 [INFO    ] (basehttp.log_message) "GET /accounts/github/login/callback/?code=262761f1a7dd111378b0&state=CZ0dywjbdVWwstxy HTTP/1.1" 302 0
2023-11-20 17:54:45 [INFO    ] (basehttp.log_message) "GET / HTTP/1.1" 200 13639
2023-11-20 17:54:45 [INFO    ] (basehttp.log_message) "GET / HTTP/1.1" 200 13639
2023-11-20 17:54:48 [INFO    ] (basehttp.log_message) "GET /users/profile/14 HTTP/1.1" 200 15852
2023-11-20 17:54:48 [INFO    ] (basehttp.log_message) "GET /users/profile/14 HTTP/1.1" 200 15852
2023-11-20 17:54:48 [INFO    ] (basehttp.log_message) "GET /static/vendor/css/profile.css HTTP/1.1" 200 31
2023-11-20 17:54:48 [INFO    ] (basehttp.log_message) "GET /static/vendor/css/profile.css HTTP/1.1" 200 31
2023-11-20 17:54:48 [INFO    ] (basehttp.log_message) "GET /static/vendor/img/users/default_avatar.jpg HTTP/1.1" 200 15700
2023-11-20 17:54:48 [INFO    ] (basehttp.log_message) "GET /static/vendor/img/users/default_avatar.jpg HTTP/1.1" 200 15700
2023-11-20 17:54:53 [INFO    ] (basehttp.log_message) "GET /users/profile/14 HTTP/1.1" 200 15852
2023-11-20 17:54:53 [INFO    ] (basehttp.log_message) "GET /users/profile/14 HTTP/1.1" 200 15852
2023-11-20 18:01:07 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2023-11-20 18:01:07 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2023-11-20 18:01:08 [INFO    ] (basehttp.log_message) "GET /admin/ HTTP/1.1" 302 0
2023-11-20 18:01:08 [INFO    ] (basehttp.log_message) "GET /admin/ HTTP/1.1" 302 0
2023-11-20 18:01:08 [INFO    ] (basehttp.log_message) "GET /admin/login/?next=/admin/ HTTP/1.1" 200 12587
2023-11-20 18:01:08 [INFO    ] (basehttp.log_message) "GET /admin/login/?next=/admin/ HTTP/1.1" 200 12587
2023-11-20 18:01:10 [INFO    ] (basehttp.log_message) "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
2023-11-20 18:01:10 [INFO    ] (basehttp.log_message) "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
2023-11-20 18:01:10 [INFO    ] (basehttp.log_message) "GET /admin/ HTTP/1.1" 200 22169
2023-11-20 18:01:10 [INFO    ] (basehttp.log_message) "GET /admin/ HTTP/1.1" 200 22169
2023-11-20 18:01:18 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialapp/ HTTP/1.1" 200 20860
2023-11-20 18:01:18 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialapp/ HTTP/1.1" 200 20860
2023-11-20 18:01:18 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 18:01:18 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 18:01:19 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialapp/1/change/ HTTP/1.1" 200 24992
2023-11-20 18:01:19 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialapp/1/change/ HTTP/1.1" 200 24992
2023-11-20 18:01:19 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 18:01:19 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 18:02:01 [INFO    ] (basehttp.log_message) "GET /admin/sites/site/ HTTP/1.1" 200 21485
2023-11-20 18:02:01 [INFO    ] (basehttp.log_message) "GET /admin/sites/site/ HTTP/1.1" 200 21485
2023-11-20 18:02:02 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 18:02:02 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 18:02:03 [INFO    ] (basehttp.log_message) "GET /admin/sites/site/2/change/ HTTP/1.1" 200 20658
2023-11-20 18:02:03 [INFO    ] (basehttp.log_message) "GET /admin/sites/site/2/change/ HTTP/1.1" 200 20658
2023-11-20 18:02:03 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 18:02:03 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 18:07:04 [INFO    ] (basehttp.log_message) "GET /admin/sites/site/ HTTP/1.1" 200 21485
2023-11-20 18:07:04 [INFO    ] (basehttp.log_message) "GET /admin/sites/site/ HTTP/1.1" 200 21485
2023-11-20 18:07:05 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 18:07:05 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 18:07:20 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialapp/ HTTP/1.1" 200 20860
2023-11-20 18:07:20 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialapp/ HTTP/1.1" 200 20860
2023-11-20 18:07:20 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 18:07:20 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 18:07:22 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialapp/1/change/ HTTP/1.1" 200 24992
2023-11-20 18:07:22 [INFO    ] (basehttp.log_message) "GET /admin/socialaccount/socialapp/1/change/ HTTP/1.1" 200 24992
2023-11-20 18:07:22 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 18:07:22 [INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 15618
2023-11-20 18:08:00 [INFO    ] (autoreload.trigger_reload) C:\Users\Дом\Desktop\mystore-server\mystore\mystore\settings.py changed, reloading.
2023-11-20 18:08:00 [INFO    ] (autoreload.trigger_reload) C:\Users\Дом\Desktop\mystore-server\mystore\mystore\settings.py changed, reloading.
2023-11-20 18:08:02 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2023-11-20 18:08:02 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
